### ISSUE TITLE
Repository Status

### ISSUE THREAD

**Issue by JacobCallahan** [RedHatQE/openshift-resources-definitions#3]
Hi @myakove, we're checking in to see the status of this repository as part of an organization-level evaluation. Can you let us know the following?

1. Is this being actively developed/maintained?
2. Is this project in active use?
3. If not you, who is the primary contact for this project?

Thanks!

**Comment by myakove** [comment]
This project in use daily.

**Comment by JacobCallahan** [comment]
Thanks for the response
